
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "moddatetime" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE TYPE "public"."friend_request_status" AS ENUM (
    'pending',
    'rejected',
    'accepted'
);

ALTER TYPE "public"."friend_request_status" OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."change_user_password"("current_plain_password" character varying, "new_plain_password" character varying) RETURNS "json"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
DECLARE
_uid uuid; -- for checking by 'is not found'
user_id uuid; -- to store the user id from the request
BEGIN
  
  -- Get user by its current auth.uid and current password
  user_id := auth.uid();
  SELECT id INTO _uid
  FROM auth.users
  WHERE id = user_id
  AND encrypted_password =
  crypt(current_plain_password::text, auth.users.encrypted_password);

  -- Check the currect password
  IF NOT FOUND THEN
    RAISE EXCEPTION 'incorrect password';
  END IF;

  -- Then set the new password
  UPDATE auth.users SET 
  encrypted_password =
  crypt(new_plain_password, gen_salt('bf'))
  WHERE id = user_id;
  
  RETURN '{"data":true}';
END;
$$;

ALTER FUNCTION "public"."change_user_password"("current_plain_password" character varying, "new_plain_password" character varying) OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."insert_user_friends"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    IF NEW.status = 'accepted' THEN
        INSERT INTO public.user_friends (user_id, friend_user_id, request_id) VALUES (NEW.sender_user_id, NEW.receiver_user_id, NEW.id);
        INSERT INTO public.user_friends (user_id, friend_user_id, request_id) VALUES (NEW.receiver_user_id, NEW.sender_user_id, NEW.id);
    END IF;
    RETURN NEW;
END;
$$;

ALTER FUNCTION "public"."insert_user_friends"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."accounts" (
    "id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "spotify_refresh_token" "text",
    "spotify_token_data" "jsonb",
    "spotify_user_id" "text",
    "subscription" "uuid"
);

ALTER TABLE "public"."accounts" OWNER TO "postgres";

COMMENT ON TABLE "public"."accounts" IS 'Stores users private account info';

CREATE TABLE IF NOT EXISTS "public"."friend_requests" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "sender_user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "receiver_user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "status" "public"."friend_request_status" NOT NULL,
    CONSTRAINT "chk_user_ids" CHECK (("sender_user_id" <> "receiver_user_id"))
);

ALTER TABLE "public"."friend_requests" OWNER TO "postgres";

COMMENT ON TABLE "public"."friend_requests" IS 'A table for pending friend requests';

ALTER TABLE "public"."friend_requests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."friend_requests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."fuseTags" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "tag_id_1" bigint NOT NULL,
    "tag_id_2" bigint NOT NULL,
    "synced_at" timestamp with time zone,
    "latest_snapshot_id" "text",
    "spotify_playlist_id" "text",
    "spotify_playlist_uri" "text",
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL
);

ALTER TABLE "public"."fuseTags" OWNER TO "postgres";

COMMENT ON TABLE "public"."fuseTags" IS 'User created fuseTags';

ALTER TABLE "public"."fuseTags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."fuseTags_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "color" "text" NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "latest_snapshot_id" "text",
    "spotify_playlist_id" "text",
    "spotify_playlist_uri" "text",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "synced_at" timestamp with time zone
);

ALTER TABLE "public"."tags" OWNER TO "postgres";

COMMENT ON TABLE "public"."tags" IS 'user created tags';

COMMENT ON COLUMN "public"."tags"."latest_snapshot_id" IS 'latest snapshot of a spotify playlist';

CREATE TABLE IF NOT EXISTS "public"."trackTags" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "tag_id" bigint NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "track_id" "text" NOT NULL
);

ALTER TABLE "public"."trackTags" OWNER TO "postgres";

COMMENT ON TABLE "public"."trackTags" IS 'junction table for tracks and tags';

CREATE OR REPLACE VIEW "public"."initial_tags_with_matches" WITH ("security_invoker"='true') AS
 SELECT DISTINCT "t"."id",
    "t"."name",
    "t"."color"
   FROM ("public"."tags" "t"
     JOIN "public"."trackTags" "tt" ON (("t"."id" = "tt"."tag_id")))
  WHERE ((EXISTS ( SELECT 1
           FROM "public"."trackTags" "tt_inner"
          WHERE (("tt_inner"."track_id" = "tt"."track_id") AND ("tt_inner"."tag_id" <> "t"."id")))) AND (NOT (EXISTS ( SELECT 1
           FROM "public"."fuseTags" "ft"
          WHERE ((("ft"."tag_id_1" = "t"."id") AND ("ft"."tag_id_2" IN ( SELECT "tt_inner"."tag_id"
                   FROM "public"."trackTags" "tt_inner"
                  WHERE (("tt_inner"."track_id" = "tt"."track_id") AND ("tt_inner"."tag_id" <> "t"."id"))))) OR (("ft"."tag_id_2" = "t"."id") AND ("ft"."tag_id_1" IN ( SELECT "tt_inner"."tag_id"
                   FROM "public"."trackTags" "tt_inner"
                  WHERE (("tt_inner"."track_id" = "tt"."track_id") AND ("tt_inner"."tag_id" <> "t"."id"))))))))));

ALTER TABLE "public"."initial_tags_with_matches" OWNER TO "postgres";

CREATE OR REPLACE VIEW "public"."matched_tags" WITH ("security_invoker"='true') AS
 SELECT DISTINCT "tt1"."tag_id" AS "initial_tag_id",
    "tt2"."tag_id" AS "id",
    "t2"."name",
    "t2"."color"
   FROM (("public"."trackTags" "tt1"
     JOIN "public"."trackTags" "tt2" ON ((("tt1"."track_id" = "tt2"."track_id") AND ("tt1"."tag_id" <> "tt2"."tag_id"))))
     JOIN "public"."tags" "t2" ON (("tt2"."tag_id" = "t2"."id")))
  WHERE (NOT (EXISTS ( SELECT 1
           FROM "public"."fuseTags" "ft"
          WHERE ((("ft"."tag_id_1" = "tt1"."tag_id") AND ("ft"."tag_id_2" = "tt2"."tag_id")) OR (("ft"."tag_id_1" = "tt2"."tag_id") AND ("ft"."tag_id_2" = "tt1"."tag_id"))))));

ALTER TABLE "public"."matched_tags" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "name" "text" NOT NULL,
    "avatar_url" "text"
);

ALTER TABLE "public"."profiles" OWNER TO "postgres";

COMMENT ON TABLE "public"."profiles" IS 'Extends auth storage with additional user properties';

CREATE TABLE IF NOT EXISTS "public"."subscriptions" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "product_id" "text" NOT NULL,
    "is_sandbox" boolean NOT NULL,
    "expiration_date" timestamp with time zone,
    "will_renew" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "unsubscribed_at" timestamp with time zone,
    "billing_issue_at" timestamp with time zone,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "app_user_id" "text",
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);

ALTER TABLE "public"."subscriptions" OWNER TO "postgres";

ALTER TABLE "public"."tags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tags_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE OR REPLACE VIEW "public"."tags_with_track_ids" WITH ("security_invoker"='true') AS
 SELECT "tags"."id",
    "tags"."created_at",
    "tags"."name",
    "tags"."color",
    "tags"."user_id",
    "array_agg"("trackTags"."track_id") FILTER (WHERE ("trackTags"."track_id" IS NOT NULL)) AS "track_ids"
   FROM ("public"."tags"
     LEFT JOIN "public"."trackTags" ON (("tags"."id" = "trackTags"."tag_id")))
  GROUP BY "tags"."id", "tags"."created_at", "tags"."name", "tags"."color", "tags"."user_id";

ALTER TABLE "public"."tags_with_track_ids" OWNER TO "postgres";

ALTER TABLE "public"."trackTags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."trackTags_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE OR REPLACE VIEW "public"."track_tags_view" WITH ("security_invoker"='true') AS
 SELECT DISTINCT "trackTags"."track_id"
   FROM "public"."trackTags";

ALTER TABLE "public"."track_tags_view" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."user_friends" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "friend_user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "request_id" bigint NOT NULL,
    CONSTRAINT "chk_user_ids" CHECK (("user_id" <> "friend_user_id"))
);

ALTER TABLE "public"."user_friends" OWNER TO "postgres";

COMMENT ON TABLE "public"."user_friends" IS 'a table holding friend requests and when approved, a relation';

ALTER TABLE "public"."user_friends" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_friends_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."accounts"
    ADD CONSTRAINT "accounts_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."friend_requests"
    ADD CONSTRAINT "friend_requests_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."fuseTags"
    ADD CONSTRAINT "fuseTags_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."trackTags"
    ADD CONSTRAINT "trackTags_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."friend_requests"
    ADD CONSTRAINT "unique_user_pair" UNIQUE ("sender_user_id", "receiver_user_id");

ALTER TABLE ONLY "public"."user_friends"
    ADD CONSTRAINT "user_friends_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "users_name_key" UNIQUE ("name");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

CREATE UNIQUE INDEX "idx_unique_user_pair" ON "public"."friend_requests" USING "btree" (LEAST("sender_user_id", "receiver_user_id"), GREATEST("sender_user_id", "receiver_user_id"));

CREATE OR REPLACE TRIGGER "insert_user_friends_trigger" AFTER UPDATE OF "status" ON "public"."friend_requests" FOR EACH ROW EXECUTE FUNCTION "public"."insert_user_friends"();

CREATE OR REPLACE TRIGGER "update_updated_at" BEFORE UPDATE ON "public"."tags" FOR EACH ROW EXECUTE FUNCTION "storage"."update_updated_at_column"();

ALTER TABLE ONLY "public"."accounts"
    ADD CONSTRAINT "accounts_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."accounts"
    ADD CONSTRAINT "accounts_subscription_fkey" FOREIGN KEY ("subscription") REFERENCES "public"."subscriptions"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."friend_requests"
    ADD CONSTRAINT "friend_requests_receiver_user_id_fkey" FOREIGN KEY ("receiver_user_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."friend_requests"
    ADD CONSTRAINT "friend_requests_sender_user_id_fkey" FOREIGN KEY ("sender_user_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."fuseTags"
    ADD CONSTRAINT "public_fuseTags_tag_id_1_fkey" FOREIGN KEY ("tag_id_1") REFERENCES "public"."tags"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."fuseTags"
    ADD CONSTRAINT "public_fuseTags_tag_id_2_fkey" FOREIGN KEY ("tag_id_2") REFERENCES "public"."tags"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."fuseTags"
    ADD CONSTRAINT "public_fuseTags_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "public_tags_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."trackTags"
    ADD CONSTRAINT "public_trackTags_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "public_users_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."trackTags"
    ADD CONSTRAINT "trackTags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_friends"
    ADD CONSTRAINT "user_friends_friend_user_id_fkey" FOREIGN KEY ("friend_user_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_friends"
    ADD CONSTRAINT "user_friends_request_id_fkey" FOREIGN KEY ("request_id") REFERENCES "public"."friend_requests"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "users_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

CREATE POLICY "Enable all actions for users based on user_id" ON "public"."accounts" USING ((( SELECT "auth"."uid"() AS "uid") = "id"));

CREATE POLICY "Enable all operations for users based on user_id" ON "public"."subscriptions" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));

CREATE POLICY "Enable delete for users based on user_id" ON "public"."fuseTags" FOR DELETE USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Enable delete for users based on user_id" ON "public"."profiles" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "id"));

CREATE POLICY "Enable delete for users based on user_id" ON "public"."tags" FOR DELETE USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Enable delete for users based on user_id" ON "public"."trackTags" FOR DELETE USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Enable delete for users based on user_id" ON "public"."user_friends" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));

CREATE POLICY "Enable delete for users who created the request" ON "public"."friend_requests" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "sender_user_id"));

CREATE POLICY "Enable insert for authenticated users only" ON "public"."friend_requests" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."fuseTags" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."subscriptions" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."tags" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."trackTags" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."user_friends" FOR INSERT TO "authenticated" WITH CHECK (true);

CREATE POLICY "Enable insert for users based on user_id" ON "public"."profiles" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "id"));

CREATE POLICY "Enable read access for all authenticated users" ON "public"."profiles" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."user_friends" FOR SELECT TO "authenticated" USING (true);

CREATE POLICY "Enable read access for authenticated users" ON "public"."trackTags" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Enable read access for users present in the request" ON "public"."friend_requests" FOR SELECT TO "authenticated" USING (((( SELECT "auth"."uid"() AS "uid") = "receiver_user_id") OR (( SELECT "auth"."uid"() AS "uid") = "sender_user_id")));

CREATE POLICY "Enable select for users based on user_id" ON "public"."fuseTags" FOR SELECT USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Enable select for users based on user_id" ON "public"."tags" FOR SELECT USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Enable update for receiving users" ON "public"."friend_requests" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "receiver_user_id"));

CREATE POLICY "Enable update for users based on id" ON "public"."user_friends" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));

CREATE POLICY "Enable update for users based on user_id" ON "public"."fuseTags" FOR UPDATE USING (("auth"."uid"() = "user_id"));

CREATE POLICY "Enable update for users based on user_id" ON "public"."profiles" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "id"));

CREATE POLICY "Enable update for users based on user_id" ON "public"."tags" FOR UPDATE USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));

ALTER TABLE "public"."accounts" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."friend_requests" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."fuseTags" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."subscriptions" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tags" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."trackTags" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."user_friends" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."change_user_password"("current_plain_password" character varying, "new_plain_password" character varying) TO "anon";
GRANT ALL ON FUNCTION "public"."change_user_password"("current_plain_password" character varying, "new_plain_password" character varying) TO "authenticated";
GRANT ALL ON FUNCTION "public"."change_user_password"("current_plain_password" character varying, "new_plain_password" character varying) TO "service_role";

GRANT ALL ON FUNCTION "public"."insert_user_friends"() TO "anon";
GRANT ALL ON FUNCTION "public"."insert_user_friends"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."insert_user_friends"() TO "service_role";

GRANT ALL ON TABLE "public"."accounts" TO "anon";
GRANT ALL ON TABLE "public"."accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."accounts" TO "service_role";

GRANT ALL ON TABLE "public"."friend_requests" TO "anon";
GRANT ALL ON TABLE "public"."friend_requests" TO "authenticated";
GRANT ALL ON TABLE "public"."friend_requests" TO "service_role";

GRANT ALL ON SEQUENCE "public"."friend_requests_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."friend_requests_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."friend_requests_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."fuseTags" TO "anon";
GRANT ALL ON TABLE "public"."fuseTags" TO "authenticated";
GRANT ALL ON TABLE "public"."fuseTags" TO "service_role";

GRANT ALL ON SEQUENCE "public"."fuseTags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."fuseTags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."fuseTags_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";

GRANT ALL ON TABLE "public"."trackTags" TO "anon";
GRANT ALL ON TABLE "public"."trackTags" TO "authenticated";
GRANT ALL ON TABLE "public"."trackTags" TO "service_role";

GRANT ALL ON TABLE "public"."initial_tags_with_matches" TO "anon";
GRANT ALL ON TABLE "public"."initial_tags_with_matches" TO "authenticated";
GRANT ALL ON TABLE "public"."initial_tags_with_matches" TO "service_role";

GRANT ALL ON TABLE "public"."matched_tags" TO "anon";
GRANT ALL ON TABLE "public"."matched_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."matched_tags" TO "service_role";

GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";

GRANT ALL ON TABLE "public"."subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."subscriptions" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tags_with_track_ids" TO "anon";
GRANT ALL ON TABLE "public"."tags_with_track_ids" TO "authenticated";
GRANT ALL ON TABLE "public"."tags_with_track_ids" TO "service_role";

GRANT ALL ON SEQUENCE "public"."trackTags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."trackTags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."trackTags_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."track_tags_view" TO "anon";
GRANT ALL ON TABLE "public"."track_tags_view" TO "authenticated";
GRANT ALL ON TABLE "public"."track_tags_view" TO "service_role";

GRANT ALL ON TABLE "public"."user_friends" TO "anon";
GRANT ALL ON TABLE "public"."user_friends" TO "authenticated";
GRANT ALL ON TABLE "public"."user_friends" TO "service_role";

GRANT ALL ON SEQUENCE "public"."user_friends_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_friends_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_friends_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
